---
- name: "prometheus | Deploy Alertmanager templates"
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.vars',
      'alertmanager_instance_templates') }}"
    dest: "{{ hostvars[inventory_hostname]['alertmanager_conf_dest'] +
      '/alertmanager.tmpl' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - "lookup('ansible.builtin.vars', 'alertmanager_instance_templates',
      default='') not in ['', [], '[]', None]"
  notify:
    - "Reload Alertmanager"
- name: "prometheus | Deploy Alertmanager Gossip TLS settings"
  ansible.builtin.template:
    src: "gossip.yml.j2"
    dest: "{{ hostvars[inventory_hostname]['alertmanager_conf_dest'] +
      '/gossip.yml' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - "lookup('ansible.builtin.vars', 'alertmanager_instance_gossip',
      default='') not in ['', [], '[]', None]"
  notify:
    - "Reload Alertmanager"
- name: "prometheus | Deploy Alertmanager YAML configuration"
  ansible.builtin.template:
    src: "alertmanager.yml.j2"
    dest: "{{ hostvars[inventory_hostname]['alertmanager_conf_dest'] +
      '/alertmanager.yml' }}"
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "amtool check-config %s"
  when:
    - "lookup('ansible.builtin.vars', 'alertmanager_instance_settings',
      default='') not in ['', [], '[]', None]"
  notify:
    - "Reload Alertmanager"
- name: "prometheus | Deploy Alertmanager service configuration"
  ansible.builtin.template:
    src: "alertmanager_options.j2"
    dest: "{{ hostvars[inventory_hostname]['prometheus_options_dest'] + '/' +
      hostvars[inventory_hostname]['alertmanager_service'] }}"
    owner: "root"
    group: "root"
    mode: "0644"
  register: "alertmanager_service_settings_result"
  notify:
    - "Restart Alertmanager"
- name: "prometheus | Ensure Alertmanager service is started"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['alertmanager_service'] }}"
    state: "started"
  when:
    - "hostvars[inventory_hostname]['prometheus'] is defined"
    - "hostvars[inventory_hostname]['prometheus']
      not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(lookup('ansible.builtin.vars',
      'alertmanager_started', default='')) == 'true'"
  vars:
    alertmanager_started: "[].started[] |
      map(&alertmanager || 'false', @) | [0]"
- name: "prometheus | Enable Alertmanager service"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['alertmanager_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['prometheus'] is defined"
    - "hostvars[inventory_hostname]['prometheus']
      not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['prometheus'] |
      community.general.json_query(lookup('ansible.builtin.vars',
      'alertmanager_enable', default='')) == 'true'"
  vars:
    alertmanager_enable: "[].enable[] | map(&alertmanager || 'false', @) | [0]"
