---
- name: "prometheus | Deploy amtool configuration"
  ansible.builtin.template:
    src: "amtool.yml.j2"
    dest: "{{ hostvars[inventory_hostname]['amtool_conf_dest'] +
      '/config.yml' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - "lookup('ansible.builtin.vars', 'amtool_instance_settings',
      default='') not in ['', [], '[]', None]"
